---
title: "First Knit"
author: "JoLynn Hopkins-Butler"
date: "September 5, 2019"
output: 
  html_document:
    number_sections: true
    toc: true
---

### `r as.character(Sys.Date())`



# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. Half the points in this assignment depend on your picture and name being correct!!  Be sure to put your photo in the AAA_Owner_Info folder and call it My_photo.jpg after first renaming the current one to Koala.jpg . 

## Where are you now?  
What row are you in, front,middle or back?  Do you usually choose a similiar row in other classes? What is the computer number where you are sitting?  How on a scale of 1 to 10 (1=low, 10=high) How you feel about periodic seat re-assignment, say how and why. Teams, have you ever worked on one in a class setting?  

# my answer   

I am currently in room 124, in the back of the classroom. I usually sit in the similar area in other classes. I am using my personal laptop and there is no computer number. For periodic seat re-assignment I give it a 5. I give it a 5 because I don't mind either way. I work with teams in all of my classes. 

   
     


## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want me to call you something else - what would that be? 

# my answer     
  
   Everyone calls me JoLynn
 




# Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

# my answer     
  
My short term goal or next achievement is to obtain my MBA. Marketing woud be the greatest interest to me. As mentioned earlier, I wish to obtain my Master's Degree.
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

# my answer     
The furthest destinations I've visited was Canada, the Caribbean. Jamaica and the Bahamas. I would like to go the Europe, Japan and Dubai. I've never been in the military. If I was drafted I would definitely go to the Air Force. I would go to the Air Force because the majority of my family served in the Air Force.   
   
  




## Why are you taking Math 115?  
What grade do you need to attain in stats to not upset your future plans, What is your plan?
 

# my answer     
I took Math 115 when I went to AVC. Fortunately I passed the class years ago.
  
   
 





## Homework Help and Getting around?  
On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  Do you have a computer you can use at home? If so, what kind is it (windows, Apple, Linux)? Do you have internet access at home?  
How do you get to class? Are there issues that limit when you can be at the college?Where and when did you attend high school?  Do you currently have a job?

# my answer   
I am an expert, if you saw the movie '
SPinal TAP' I was the 11
   
  




## critique of the AI in the business article 
I agree with the majority of Building the AI-Powered Organization article. From educating everyone on the technology, providing incentives to change, and reinforcing change. I also concurred with companies breaking silos; by bringing diversified knowledge and input to obtain valuable information. However, the only thing I did not agree with is when the article states that the company shouldn’t have everything together before they start on a project, it should be trial and error. I believe that before you start any project, everything should be in order. I do know there will be changes, however, there shouldn’t be too many changes that will produce a lot of setbacks.
